apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus-config: |-
    global:
      scrape_interval: 15s
      external_labels:
        cluster_id: '{{.Values.prometheus.clusterId}}'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 15s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'pods'
        scrape_interval: 15s
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: {{ .Release.Namespace }}
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_metric_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

